---
title: "Section 2: ggplot"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---

```{r}
library(tidyverse)
stat113_df <- read_csv("https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/stat113.csv")

stat113_df

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_histogram(colour = "black", fill = "white",
                 bins = 17)

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_freqpoly(bins = 17)

ggplot(data = stat113_df, aes(x = GPA)) +
    geom_histogram(colour = "black", fill = "white", bins = 17) +
    geom_freqpoly(bins = 15)
```

Exercise 1.

```{r}
## names(stat113_df) brings up the names of all variables
```

Exercises 2 and 3.

```{r}
ggplot(data = stat113_df, aes(x = GPA)) +
  geom_histogram(colour = "dodgerblue4", fill = "dodgerblue1",
                 bins = 17)

ggplot(data = stat113_df, aes(x = GPA)) +
  geom_histogram(colour = "violetred3",
                 fill = "yellowgreen", bins = 17)
```

```{r}
ggplot(data = stat113_df, aes(x = SocialMedia)) +
  geom_bar()
```

Exercises 4 and 5

```{r}
ggplot(data = stat113_df, aes(x = Award)) +
  geom_bar(colour = "burlywood3", fill = "bisque4")
```


```{r}
ggplot(data = stat113_df, aes(x = Year, fill = SocialMedia)) +
  geom_bar() 

ggplot(data = stat113_df, aes(x = Year, fill = SocialMedia)) +
  geom_bar(position = "fill") +
  labs(y = "Proportion")
```

Exercise 6.

```{r}
ggplot(data = stat113_df, aes(x = Sex, fill = Sport)) +
  geom_bar(position = "fill") +
  labs(y = "Proportion")
## a slightly higher proportion of male students played a 
## a sport in this survey, compared to female students.
```

Exercises 7 and 8.

```{r}
ggplot(data = stat113_df, aes(x = Sport, y = Pulse)) +
  geom_violin(colour = "lightpink4", fill = "lightpink")

ggplot(data = stat113_df, aes(x = Award, y = Exercise)) +
  geom_jitter(width = 0.10)
```

## Section 2.4: Practice

Class Exercise 1. 

```{r}
stat113_restructured <- stat113_df |> group_by(SocialMedia) |>
  summarise(n_social = n())
stat113_restructured

ggplot(data = stat113_restructured, aes(x = SocialMedia)) +
  geom_bar()

## if our data is structured like this, we use geom_col() instead:

ggplot(data = stat113_restructured, aes(x = SocialMedia,
                                        y = n_social)) +
  geom_col()
```

```{r}
library(tidyverse)
fitness_full <- read_csv("https://raw.githubusercontent.com/highamm/ds234_quarto/main/data_online/higham_fitness_clean.csv",
                         col_types = list(stepgoal = col_factor())) |>
  mutate(weekend_ind = case_when(weekday == "Sat" | weekday == "Sun" ~ "weekend",
                                 TRUE ~ "weekday"))
```

```{r}
ggplot(data = fitness_full, aes(x = distance,
                                y = active_cals)) +
  geom_point() +
  geom_smooth(se = FALSE, span = 2)
## method = "lm" changes to line
## span controls how "wiggly" the smoother is
```

Class Exercise 3.

```{r}
fitness_full
ggplot(data = fitness_full, aes(x = Start,
                                y = steps)) +
  geom_line() +
  geom_smooth()

```

Class Exercise 4.

```{r}
ggplot(data = stat113_df, aes(x = Exercise,
                              y = GPA)) +
  geom_point() +
  facet_wrap(~ Sex + Sport)

ggplot(data = stat113_df |>
         filter(!is.na(Sex) & !is.na(Sport)),
       aes(x = Exercise, y = GPA)) +
  geom_point() +
  facet_grid(Sex ~ Sport)
```

Class Exercise 5.

```{r}
ggplot(data = stat113_df, aes(x = Award, y = Exercise)) +
  geom_boxplot(outlier.shape = 8)
```

Class Exercise 6. Skip

## Your Turn

Your Turn 2.



