---
title: "Section 6: Tidying"
author: "Matt Higham"
format: 
  html:
    embed-resources: true
---


## Class Exercises 

Class Exercises 2 through 4

```{r}
library(tidyverse)
library(here)
prices_df <- read_csv(here("data/UBSprices2.csv"))
prices_df
## not tidy: violates (1): each variable (year, commodity, price) should
## be in their own column, not spread across 6 columns

prices_tidy <- prices_df |> pivot_longer(2:7, names_to = "temp",
                          values_to = "price") |>
  separate(col = temp, into = c("commodity", "year"), sep = -4)

prices_rice <- prices_tidy |> filter(commodity == "rice")
ggplot(data = prices_rice, aes(x = year, y = price)) +
  geom_line(aes(group = city))

## ce 4
prices_amsterdam <- prices_tidy |> filter(city == "Amsterdam")
ggplot(data = prices_amsterdam, aes(x = year, y = price)) +
  geom_line(aes(group = commodity, colour = commodity)) +
  scale_colour_viridis_d() +
  theme_minimal()

ggplot(data = prices_amsterdam, aes(x = year, y = price)) +
  geom_line() +
  scale_colour_viridis_d() +
  theme_minimal()
```

Class Exercises 5 through 7.

```{r}
mortality_df <- read_csv(here("data/under5mortality.csv"))
mortality_df

mortality_long <- mortality_df |> pivot_longer(2:217, names_to = "year",
                             values_to = "mortality") |>
  rename(country = `Under five mortality`) |>
  mutate(year = as.numeric(year))

ggplot(data = mortality_long, aes(x = year, y = mortality)) +
  geom_line(aes(group = country), alpha = 0.2)
## some lines might be flat if the graph is using a century-long
## measurement for mortality
```

Your Turn 

Your Turn 1.

```{r}
library(tidyverse)
library(here)
baseball_df <- read_csv(here("data/mlb2016.csv"))
glimpse(baseball_df)
baseball_df

## 4 is violated here: there are dollar signs in some of the variables, which are units
## Years actually contains three variables, not one (it has
## contract duration, start year, and end year)
```

Your Turns 2 through 4

```{r}
baseball_df <- baseball_df |> separate(Years, c("duration", "temp"),
                        sep = " ") |>
  separate(temp, c("Start", "End"), sep = "-")
## warning since, for one year contracts, there is no dash

baseball_df <- baseball_df |>
  mutate(Salary = parse_number(Salary),
         Total.Value = parse_number(Total.Value),
         Avg.Annual = parse_number(Avg.Annual),
         Start = parse_number(Start),
         End = parse_number(End))
baseball_df


```

Your Turn 5.

```{r}
## BAD
ggplot(data = baseball_df, aes(x = POS, y = Salary)) +
  geom_col()

ggplot(data = baseball_df, aes(x = POS, y = Salary)) +
  geom_boxplot()
ggplot(data = baseball_df, aes(x = Salary)) +
  geom_histogram(colour = "skyblue4", fill = "skyblue1",
                 bins = 15) +
  facet_wrap(~ POS)
```

Your Turn 6.

```{r}
nfl_df <- read_csv(here::here("data/nfl_salary.csv"))
nfl_df
## not tidy since position should be in its own column
## and salary should be in its own column
```

Your Turn 7 and 8.

```{r}
nfl_long <- nfl_df |> pivot_longer(2:11, names_to = "position",
                       values_to = "salary")
nfl_long

nfl_max <- nfl_long |> group_by(position, year) |>
  arrange(desc(salary)) |>
  slice(1)

##OR
nfl_long |> group_by(position, year) |>
  summarise(max_salary = max(salary, na.rm = TRUE))
## OR
nfl_long |> group_by(position, year) |>
  filter(salary == max(salary, na.rm = TRUE))

ggplot(data = nfl_max, aes(x = year, y = salary)) +
  geom_line(aes(group = position, colour = position))
```

Your Turn 9. Re-make this plot but instead of max salary, we plot the average of the top 32 players for each position in each year.

```{r}
nfl_32 <- nfl_long |> group_by(position, year) |>
  arrange(desc(salary)) |>
  slice(1:32) |>
  summarise(mean_salary = mean(salary, na.rm = TRUE))
nfl_32
ggplot(data = nfl_32, aes(x = year, y = mean_salary)) +
  geom_line() +
  facet_wrap(~ position)
```


Your Turn 10.

```{r}
## inflation rate was 11.69%
nfl_adj <- nfl_long |> filter(year == 2011 | year == 2018) |>
  mutate(salary_adj = if_else(year == 2011,
                              true = salary * 1.1169,
                              false = salary)) |>
  group_by(position, year) |>
  arrange(desc(salary_adj)) |>
  slice(1:32) |>
  summarise(mean_salary = mean(salary_adj, na.rm = TRUE))
  
ggplot(data = nfl_adj, aes(x = year, y = mean_salary)) +
  geom_line() +
  facet_wrap(~position)
```

Your Turn 11.

```{r}
nfl_rank <- nfl_long |> filter(year == 2018) |>
  group_by(position) |>
  mutate(rank_salary = rank(desc(salary)))

ggplot(data = nfl_rank, aes(x = rank_salary, y = salary)) +
  geom_line(aes(colour = position), show.legend = FALSE) +
  facet_wrap(~ position) +
  theme_minimal() +
  scale_colour_viridis_d()
```

```{r}
library(babynames)
babynames_10 <- babynames |> filter(year == 2017 & sex == "F") |>
  arrange(desc(n)) |>
  slice(1:10) |>
  mutate(name2 = fct_reorder(name, n))
babynames_10
ggplot(babynames_10, aes(x = n, y = name2)) +
  geom_col()
```





